import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const args = process.argv.slice(2);
const prod = args.includes("production");
const watch = args.includes("--watch");

const buildOptions = {
  banner: {
    js: banner,
  },
  minify: prod,
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "codemirror",
    "@codemirror/closebrackets",
    "@codemirror/commands",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "es2016",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

const watchOptions = watch
  ? {
      watch: {
        onRebuild(error) {
          if (error) {
            console.error("Rebuild failed:", error);
            return;
          }

          console.log("Rebuild succeeded.");
        },
      },
    }
  : {};

esbuild
  .build({
    ...buildOptions,
    ...watchOptions,
  })
  .then(() => {
    if (watch) {
      console.log("Watching for changes...");
    }
  })
  .catch(() => process.exit(1));
